### ISSUE TITLE
statin_sim_data.csv not found

### ISSUE THREAD

**Issue by kingfish777** [pzivich/publications-code#1]
Hi there,

Where is statin_sim_data.csv generated?

Thanks!
Scott

**Comment by pzivich** [comment]
Hi @kingfish777 which paper are you referring to?

**Comment by pzivich** [comment]
Ohh you mean `/DoubleCrossFit/` (sorry I have statins as an example in a few). The data is generated [here](https://github.com/pzivich/publications-code/blob/master/DoubleCrossFit/Python/dgm.py) which will generate the .csv file

It takes up a fair bit of space, so I didn't upload the .csv file to GitHub, just the python file for data generation
